(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.num_animation = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {idle:0,action:30};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_29 = function() {
		this.gotoAndPlay(1);
	}
	this.frame_60 = function() {
		this.gotoAndPlay(1);
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(29).call(this.frame_29).wait(31).call(this.frame_60).wait(1));

	// Layer_1
	this.text = new cjs.Text("1", "bold 40px 'NanumGothicExtraBold'", "#6FA0A8");
	this.text.textAlign = "center";
	this.text.lineHeight = 48;
	this.text.lineWidth = 100;
	this.text.parent = this;
	this.text.setTransform(0,-23);

	this.timeline.addTween(cjs.Tween.get(this.text).wait(3).to({text:"2"},0).wait(3).to({text:"3"},0).wait(3).to({text:"4"},0).wait(3).to({text:"5"},0).wait(3).to({text:"6"},0).wait(3).to({text:"7"},0).wait(3).to({text:"8"},0).wait(3).to({text:"9"},0).wait(3).to({text:"10"},0).wait(3).to({text:"0000"},0).wait(4).to({scaleX:1.3654,scaleY:1.3654,y:-31.4},0).wait(5).to({scaleX:1,scaleY:1,y:-23},0).wait(5).to({scaleX:1.3654,scaleY:1.3654,y:-31.4},0).wait(5).to({scaleX:1,scaleY:1,y:-23},0).wait(12));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-71,-34.1,142,68.30000000000001);


(lib.img_btn = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#585151").s().p("AQuDFIg0AAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA0AAIAIAAQABABAAAAQABAAAAAAQABAAAAAAQAAABABAAIABADIAAABQAAAAAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAIgIAAgAOCDFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgAMKDFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgAKSDFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgAIaDFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgAGiDFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgAEqDFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgACyDFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgAA6DFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgAg9DFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAAAAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQAAAAAAAAQgBAAAAAAgAi1DFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgAktDFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgAmlDFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgAodDFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgAqVDFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgAsNDFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgAuFDFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgAv9DFQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABgBIA8AAQAAABABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAgAw5DFQgjgCgWgRQgBAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQABAAAAAAQAAAAABgBQABAAAAAAQAAAAABABQAAAAABAAQAAAAABAAQAUAPAgACQABAAAAAAQAAAAABABQAAAAABAAQAAAAABABQAAAAAAABQAAAAABAAQAAABAAAAQAAABAAAAIAAABIgCADIgDABIgBAAgARwC0QgBAAAAAAQgBAAAAgBQgBAAAAAAQAAgBgBAAIAAAAIgBgEQAAAAAAgBQABAAAAgBQAAAAABAAQAAgBAAAAQAWgQAHgfQAAgBAAAAQAAAAABgBQAAAAAAgBQABAAAAAAIADgBIABAAQAAAAABABQAAAAABAAQAAAAAAABQABAAAAAAQAAABAAAAQABABAAAAQAAABAAAAQAAABAAAAQgIAjgZASIgDABIAAAAgAyQCBQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQgDgOAAgSIAAgdQAAgBAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABIAAAdQAAAQADAOQAAABAAAAQAAABAAAAQAAABAAAAQAAABgBAAIgCADIgBAAIgBAAIgCgBgASOBGQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAIAAg9QAAAAAAAAQAAgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAABQAAAAAAABQABAAAAABQAAAAAAAAIAAA9QAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAgAyUAHQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAAAIAAg8QAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAIAAA8QAAAAAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAgASOgxQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAIAAgoQAAgLgCgKQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQABAAAAAAQAAgBABAAQAAAAABAAQAAAAAAgBIABAAIADABQABABAAAAQAAABABAAQAAAAAAABQAAAAAAABQACALAAALIAAAoQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAgAyQhuIAAAAQgBAAAAAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAFgjAVgUQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAgBQABABAAAAQABAAAAAAQABAAAAAAQAAABABAAIAAAAIABAEQAAAAAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgTASgEAgQAAAAAAABQgBAAAAABQAAAAAAAAQgBABAAAAIgDABIgBAAgAR0ikQgSgSghgDQAAgBgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAABQAlAEAUAUQABAAAAABQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABgBAAQAAABAAAAQAAABgBAAQAAAAgBABQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAgBgBAAgAxBi6QgBgBAAAAQAAgBgBAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABAAQAAgBAAAAQABgBAAAAQABAAAAAAQABAAAAAAIASgBIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABIg8AAIgRABIAAAAIgDgBgAPKi6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgANSi6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgALai6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgAJii6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgAHqi6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgAFyi6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgAD6i6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgACCi6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgAAKi6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgAhti6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgAjli6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgAldi6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgAnVi6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgApNi6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgArFi6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgAs9i6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABgAu1i6QAAgBgBAAQAAAAgBAAQAAAAAAAAQgBgBAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAAAAAgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAAgBABAAQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAIA8AAQABAAAAAAQABAAAAAAQABAAAAAAQAAABABAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABgBAAQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAgBAAQAAAAgBABg");
	this.shape.setTransform(-0.025,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E7FBFF").s().p("APDDBQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQAAAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgyAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQAAgBgBAAQAAAAgBgBQAAAAAAAAQgBAAAAAAQgBAAAAgBIg8AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIgrAAIgGAAIAAgBQAAAAAAgBQAAAAAAgBQgBAAAAAAQAAgBAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAQAAAAgBAAQgggCgUgPQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAgBAAQgBABAAAAQAAAAgBAAQAAAAgBABQAAAAAAABQgTgQgHgaIADgDQABAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQgDgOAAgQIAAgdQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIAAgzQABAAAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAAAIAAg8QAAAAAAAAQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBAAIAAggIABgSIAEgBQAAAAABgBQAAAAAAAAQAAgBABAAQAAgBAAAAQAEggATgSQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAAAIgBgEQASgPAegEQAAABAAAAQAAABAAAAQABAAAAABQAAAAABABQAAAAABAAQAAAAAAAAQABABAAAAQABAAAAAAIARgBIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAxAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAyAAQAAABAAAAQAAABABAAQAAABAAAAQAAABABAAQAAAAABABQAAAAAAAAQABAAAAAAQABAAAAABIA8AAQABgBAAAAQABAAAAAAQABAAAAAAQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAAAgBIAjAAIAPABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAAAQABABAAAAQABAAAAAAQABAAAAABQAhADASASQABAAAAABQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQAAAAAAAAQABgBAAAAQAQARAFAcIgBAAQAAABAAAAQgBAAAAAAQgBAAAAABQAAAAgBAAQAAABAAAAQgBABAAAAQAAABAAAAQAAABAAAAQACAKAAALIAAAoQAAAAAAAAQAAABAAAAQAAABABAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAQAAAAABAAIAAAyQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAAAIAAA9QAAAAAAAAQAAABAAAAQAAABABAAQAAABAAAAQABAAAAABQAAAAABAAQAAAAABAAQAAAAABAAIAAAWQAAAOgDANIgDABQAAAAgBAAQAAABAAAAQgBABAAAAQAAAAAAABQgHAfgWAQQAAAAAAABQgBAAAAAAQAAABgBAAQAAABAAAAIABAEQgTAMgeACIgBgDQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBgBIgIAAIg0AAQgBABAAAAQgBAAAAAAQgBAAAAAAQAAABgBAAQAAAAAAABQgBAAAAABQAAAAAAABQAAAAAAABg");
	this.shape_1.setTransform(-0.025,0);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.img_btn, new cjs.Rectangle(-118,-20.2,236,40.5), null);


(lib.scene_title_bg = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgY/AlgMAAAhK/MAx/AAAMAAABK/g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.scene_title_bg, new cjs.Rectangle(-160,-240,320,480), null);


(lib.btn_retry = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.text = new cjs.Text("Application RUN", "bold 23px 'NanumGothicExtraBold'", "#A5D2D9");
	this.text.textAlign = "center";
	this.text.lineHeight = 28;
	this.text.lineWidth = 273;
	this.text.parent = this;
	this.text.setTransform(0,-13.25);

	this.timeline.addTween(cjs.Tween.get(this.text).wait(1).to({color:"#E7FCFF"},0).wait(1).to({scaleX:0.9408,scaleY:0.9408,y:-12.4412},0).wait(1));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6FA0A8").s().p("A3vGVIAAspMAvfAAAIAAMpg");
	this.shape.setTransform(0,0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#A5D2D9").s().p("A3vGVIAAspMAvfAAAIAAMpg");
	this.shape_1.setTransform(0,0.025);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6FA0A8").s().p("A2WF9IAAr5MAssAAAIAAL5g");
	this.shape_2.setTransform(0.05,0.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-152,-40.5,304.1,81.1);


(lib.btn_game_start = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_2
	this.text = new cjs.Text("Application RUN", "bold 23px 'NanumGothicExtraBold'", "#A5D2D9");
	this.text.textAlign = "center";
	this.text.lineHeight = 28;
	this.text.lineWidth = 273;
	this.text.parent = this;
	this.text.setTransform(0,-13.25);

	this.timeline.addTween(cjs.Tween.get(this.text).wait(1).to({color:"#E7FCFF"},0).wait(1).to({scaleX:0.9408,scaleY:0.9408,y:-12.4412},0).wait(1));

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#6FA0A8").s().p("A3vGVIAAspMAvfAAAIAAMpg");
	this.shape.setTransform(0,0.025);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#A5D2D9").s().p("A3vGVIAAspMAvfAAAIAAMpg");
	this.shape_1.setTransform(0,0.025);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#6FA0A8").s().p("A2WF9IAAr5MAssAAAIAAL5g");
	this.shape_2.setTransform(0.05,0.025);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-152,-40.5,304.1,81.1);


(lib.scene_title = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.text = new cjs.Text("TEST", "bold 71px 'NanumGothicExtraBold'", "#6FA0A8");
	this.text.textAlign = "center";
	this.text.lineHeight = 84;
	this.text.lineWidth = 169;
	this.text.parent = this;
	this.text.setTransform(0,-65.75);

	this.btn_start = new lib.btn_game_start();
	this.btn_start.name = "btn_start";
	this.btn_start.setTransform(0,192.7);
	new cjs.ButtonHelper(this.btn_start, 0, 1, 2);

	this.text_1 = new cjs.Text("AutoKey", "bold 40px 'NanumGothicExtraBold'", "#6FA0A8");
	this.text_1.textAlign = "center";
	this.text_1.lineHeight = 48;
	this.text_1.lineWidth = 169;
	this.text_1.parent = this;
	this.text_1.setTransform(0,-117.75);

	this.instance = new lib.scene_title_bg();
	this.instance.cache(-162,-242,324,484);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.text_1},{t:this.btn_start},{t:this.text}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.scene_title, new cjs.Rectangle(-160,-240,320,480), null);


(lib.btn_test_select = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(5));

	// Layer_2
	this.text = new cjs.Text("select", "bold 23px 'NanumGothicExtraBold'", "#A5D2D9");
	this.text.name = "text";
	this.text.textAlign = "center";
	this.text.lineHeight = 28;
	this.text.lineWidth = 194;
	this.text.parent = this;
	this.text.setTransform(-0.05,-13.25);

	this.timeline.addTween(cjs.Tween.get(this.text).wait(5));

	// Layer_1
	this.instance = new lib.img_btn();
	this.instance.cache(-120,-22,240,45);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({scaleX:0.9,scaleY:0.9},0).wait(4));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-117.5,-19.7,235,39.5);


(lib.scene_result = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(2));

	// msg
	this.msg = new cjs.Text("result -5", "bold 40px 'NanumGothicExtraBold'", "#6FA0A8");
	this.msg.name = "msg";
	this.msg.textAlign = "center";
	this.msg.lineHeight = 48;
	this.msg.lineWidth = 293;
	this.msg.parent = this;
	this.msg.setTransform(0.5,-120.8);

	this.timeline.addTween(cjs.Tween.get(this.msg).wait(1).to({text:"result 5"},0).wait(1));

	// Layer_1
	this.btn_retry = new lib.btn_retry();
	this.btn_retry.name = "btn_retry";
	this.btn_retry.setTransform(0.95,142.7);
	new cjs.ButtonHelper(this.btn_retry, 0, 1, 2);

	this.instance = new lib.scene_title_bg();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.btn_retry}]}).wait(2));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-160,-240,320,480);


(lib.scene_main = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.btn_select_3 = new lib.btn_test_select();
	this.btn_select_3.name = "btn_select_3";
	this.btn_select_3.setTransform(0.95,194.7);

	this.num_animation = new lib.num_animation();
	this.num_animation.name = "num_animation";
	this.num_animation.setTransform(-0.05,-172.8);

	this.btn_select_2 = new lib.btn_test_select();
	this.btn_select_2.name = "btn_select_2";
	this.btn_select_2.setTransform(0.95,143.7);

	this.btn_select_1 = new lib.btn_test_select();
	this.btn_select_1.name = "btn_select_1";
	this.btn_select_1.setTransform(0.95,92.7);

	this.msg = new cjs.Text("Message", "bold 40px 'NanumGothicExtraBold'", "#6FA0A8");
	this.msg.name = "msg";
	this.msg.textAlign = "center";
	this.msg.lineHeight = 48;
	this.msg.lineWidth = 293;
	this.msg.parent = this;
	this.msg.setTransform(0.5,-120.8);

	this.instance = new lib.scene_title_bg();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.msg},{t:this.btn_select_1},{t:this.btn_select_2},{t:this.num_animation},{t:this.btn_select_3}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.scene_main, new cjs.Rectangle(-160,-240,320,480), null);


// stage content:
(lib.index = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0];
	// timeline functions:
	this.frame_0 = function() {
		this.stop();
		
		
		this.scene_result.btn_retry.addEventListener("click",clickRetry.bind(this));
		
		function clickRetry()
		{	
			this.gotoAndStop(1);
			console.log("결과창");
		}
		this.scene_main.btn_select_1.text.text = "select +1";
		this.scene_main.btn_select_2.text.text = "select -1";
		this.scene_main.btn_select_3.text.text = "select -2";
		
		this.scene_main.btn_select_1.addEventListener("mousedown",selectBtn.bind(this));
		this.scene_main.btn_select_2.addEventListener("mousedown",selectBtn.bind(this));
		this.scene_main.btn_select_3.addEventListener("mousedown",selectBtn.bind(this));
		
		var value  = 0;
		
		this.scene_main.msg.text = value;
		
		
		function selectBtn(e)
		{	
		
			e.currentTarget.gotoAndPlay(1);
			this.scene_main.num_animation.gotoAndPlay("action");
		
			if(e.currentTarget.name == "btn_select_1")
			{
				value++;
				//this.scene_main.msg.text = "1";
			}
			else if(e.currentTarget.name == "btn_select_2")
			{		
				value--;
				//this.scene_main.msg.text = "2";
			}
			else if(e.currentTarget.name == "btn_select_3")
			{		
				value--;
				value--;
				//this.scene_main.msg.text = "2";
			}
			
			this.scene_main.msg.text = value;	
			console.log(value);
		
			if(value <= -5)
			{			
				this.gotoAndStop(2);
				this.scene_result.gotoAndStop(0);
				
				value = 0;
				this.scene_main.msg.text = value;
				this.scene_main.num_animation.gotoAndPlay("idle");
				e.currentTarget.gotoAndStop(0);
				
			}
			else if(value >= 5)
			{
				this.gotoAndStop(2);
				this.scene_result.gotoAndStop(1);
				
				value = 0;
				this.scene_main.msg.text = value;
				this.scene_main.num_animation.gotoAndPlay("idle");
				e.currentTarget.gotoAndStop(0);
				
			}
		}
		
		
		
		
		
		
		
		//this.addEventListener("tick",enterFrame.bind(this));
		this.scene_title.btn_start.addEventListener("click",goToMain.bind(this));
		
		function goToMain()
		{	
			this.gotoAndStop(1);		
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(3));

	// scene
	this.scene_result = new lib.scene_result();
	this.scene_result.name = "scene_result";
	this.scene_result.setTransform(956.15,240);

	this.scene_main = new lib.scene_main();
	this.scene_main.name = "scene_main";
	this.scene_main.setTransform(564.1,240);

	this.scene_title = new lib.scene_title();
	this.scene_title.name = "scene_title";
	this.scene_title.setTransform(160,240);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.scene_title},{t:this.scene_main,p:{x:564.1}},{t:this.scene_result,p:{x:956.15}}]}).to({state:[{t:this.scene_main,p:{x:160}}]},1).to({state:[{t:this.scene_result,p:{x:160}}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(160,240,956.2,240);
// library properties:
lib.properties = {
	id: 'FD4264F88CFC5A46A43E85A8E3CE96B1',
	width: 320,
	height: 480,
	fps: 60,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['FD4264F88CFC5A46A43E85A8E3CE96B1'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;